### ISSUE TITLE
System master volume reset to 100% after track switch

### ISSUE THREAD

**Issue by forivall** [tiliado/nuvola-app-rdio#2]
System master volume reset to 100% after track switch. KDE Plasma 5 desktop, IIRC, it also happened on KDE4. Manjaro linux (Arch-based), KMix, pulseaudio.
I've had this issue for a while, crossing my fingers that it would eventually go away.

```
extra/plasma-desktop 5.3.2-2
extra/pulseaudio 6.0-2
extra/kdemultimedia-kmix 15.04.3-1
local/nuvolaplayer-git 2015.04.03.bf15934-1
```

I'm not sure if this is a Rdio-specific issue, but I figured it should go here first.

My current workaround is to lower the volume within rdio, and use the physical volume knob on my headphones and speakers.

Additionally, the volume slider within rdio sets the pulseaudio per-application volume level as well, which makes it tough to precisely control the volume (since it's like `y=x^2` instead of just `y=x`). On track switch, the rdio in-app volume is also reset to the pulseaudio per-application volume, if it has been changed to anything different. This could be a separate issue, but they're probably linked.

**Comment by jiri-janousek** [comment]
Hello. Thanks for taking the time to report this issue. I'll take a look at it in [August 2015](https://github.com/tiliado/nuvolaplayer.project/issues/5) as [funds for July 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201507/) have been already almost spent. Thanks for your understanding.

**Comment by jiri-janousek** [comment]
Hello. I need more information to investigate your issue further. What's the output of following command regarding the PulseAudio flat volumes configuration option?

```
$ grep flat-volumes /etc/pulse/* ~/.pulse/* 2>/dev/null
```

I'm not sure whether I understand your issue correctly.
1. You have set volume to 100% in Rdio web interface.
2. Rdio sets Nuvola Player stream's volume to 100% on a new track.
3. Finally, your system master volume is set to 100% as well.

Is this correct? If yes, what behavior do you expect?

I also don't understand your workaround. If you set Rdio volume (the slider in the web interface) to a level that's comfortable for you, why do you need to use also hardware volume knobs?

> Additionally, the volume slider within rdio sets the pulseaudio per-application volume level as well, which makes it tough to precisely control the volume (since it's like y=x^2 instead of just y=x). On track switch, the rdio in-app volume is also reset to the pulseaudio per-application volume, if it has been changed to anything different. This could be a separate issue, but they're probably linked.

What do you exactly mean by "the pulseaudio per-application volume" and "the rdio in-app volume"?

**Comment by forivall** [comment]
```
❯ grep flat-volumes /etc/pulse/* ~/.pulse/*
/etc/pulse/daemon.conf:57:; flat-volumes = yes
grep: /home/forivall/.pulse/*: No such file or directory
```

By per-application volume, I mean the Nuvola Player stream volume.
By in-app volume, I mean the slider in the web interface.

<s>Since the web interface controls volume itself, the volume control turns from a [y=x](http://www.wolframalpha.com/input/?i=y%3Dx) control to a [y=x<sup>2</sup>](http://www.wolframalpha.com/input/?i=y%3Dx^2) kind of control (where y is the volume and x is the slider position), which is why the workaround of hardware volume knobs is needed, in order to get that fine control at the low end.</s> nvm, upon further investigation, this is not the case.

**Comment by forivall** [comment]
I looked into pulseaudio flat-volumes, and set it to `no`, and that also is a better workaround for the issue.

**Comment by forivall** [comment]
Exact same issue as https://github.com/tiliado/nuvolaplayer/issues/84 ; I guess this can be closed?

**Comment by jiri-janousek** [comment]
> I looked into pulseaudio flat-volumes, and set it to `no`, and that also is a better workaround for the issue.

Actually, it is not a workaround. The behavior you have previously described is completely correct with flat-volumes enabled. The only issue is that you actually don't want that behavior and you have to change your PulseAudio settings accordingly (to disable flat-volumes).

> Exact same issue as tiliado/nuvolaplayer#84

No, that issue was about different volumes of two audio streams. The only similarity is that the flat-volumes feature makes everything worse as it is broken by design. That's why flat-volumes are disabled by default in Ubuntu.

I'm closing this issue as the cause was wrong PulseAudio configuration on your system.

**Comment by jiri-janousek** [comment]
Follow up: tiliado/nuvolaplayer#138

**Comment by jiri-janousek** [comment]
> > Exact same issue as tiliado/nuvolaplayer#84
> 
> No, that issue was about different volumes of two audio streams. The only similarity is that the flat-volumes feature makes everything worse as it is broken by design. That's why flat-volumes are disabled by default in Ubuntu.

Actually, you are right. I didn't read the bug carefully and thought you were talking about tiliado/nuvola-app-spotify#6.

**Comment by fenryxo** [comment]
Follow up: tiliado/nuvolaplayer#138

**Comment by forivall** [comment]
Flat volumes would have worked if the slider in the web interface updated when the stream volume is changed from outside of the app, however, that's probably trickier to do (https://github.com/tiliado/nuvolaplayer/issues/22 ??).

&lt;ramble> I suppose that flat volumes works in windows because they probably introduced a new api to control the flat volume, whereas pulse made the change while still using the same api, so apps that didn't expect to control the global volume ended up changing the global volume. &lt;/ramble>
